version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    network_mode: bridge
    privileged: true
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - LOCALSTACK_HOSTNAME=localhost
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"